### ISSUE TITLE
basic tests down work with httpunit

### ISSUE THREAD

**Issue by simbo1905** [mlex/geb-demo#3]
Trying out: 

``` sh
cd basic
mvn -Dgeb.env=htmlunit test
```

It fails with: 

``` sh
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.186 sec <<< FAILURE!
create a new movie(SimpleSpec)  Time elapsed: 0.185 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasInputDevices
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
```

**Comment by simbo1905** [comment]
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T12:57:37+01:00)
Maven home: /usr/local/Cellar/maven333
Java version: 1.7.0_15, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_15.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.1", arch: "x86_64", family: "mac"

```

**Comment by simbo1905** [comment]
This is fixed by including `selenium-remote-driver` i will setup a PR. 

``` xml
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>2.28.0</version>
            <scope>test</scope>
        </dependency>
```
